analytics: {}
color:
  brandColors:
    - '#B8B090'
    - '#182848'
    - '#A8A058'
    - '#C0C860'
    - '#D0D890'
  brandStrength: 0.049718
  lightness: 0
  rhythmicContrast: 0.902027
  saturation: 0.898187
cta: {}
layout_spectrum: 0.368243
name: Deepdfspicks
opengraph: {}
purpose: {}
typography_spectrum: 0.131756
